services:
  spark:
    version: 2.2.0    
  hdfs:
    version: 2.7.3   
provider: ec2

providers:
  ec2:
    key-name: oxclo
    identity-file: /home/haihao/keys/oxclo.pem
    instance-type: m3.medium
    region: ap-southeast-2
    # availability-zone: <name>
    ami: ami-30041c53   # Amazon Linux, ap-southeast-2
    user: ec2-user
   
    tenancy: default  # default | dedicated
    ebs-optimized: no  # yes | no
    instance-initiated-shutdown-behavior: terminate  # terminate | stop

launch:
  num-slaves: 19

debug: false
